---
- name: Verify
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Read /etc/motd
      ansible.builtin.slurp:
        src: /etc/motd
      register: motd

    - name: Owner line is present
      ansible.builtin.assert:
        that: "'Owner: molecule@example.com' in (motd.content | b64decode)"
